version: "3.8"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    image: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/code
  frontend:
    depends_on:
      - backend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    image: frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"

    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - ./frontend:/app
