FROM python:3.9.10 AS builder

COPY ./requirements.txt .

RUN pip install --user -r requirements.txt

RUN useradd -u 1000 nonroot
# Change to non-root privilege
USER nonroot

FROM python:3.9.10-slim
WORKDIR /code

COPY --from=builder /root/.local /root/.local
COPY . .

ENV PATH=/root/.local/bin:$PATH
ENV FLASK_APP=src/app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV=development

EXPOSE 5000

CMD [ "flask", "run", "--host", "0.0.0.0" ]